name=input("enter the name")
standard=int(input("enter the standard"))
address=input("enter the address")
gender=input("enter the Sir or Madam")
sub=input("enter the subject")
place=input("enter the place")
date=(input("enter the date"))

print(" ")
print("\t\t\tLeave Letter")
print(" ")
print("From:")
print("\t",name)
print("\t",standard)
print("\t",address)
print(" ")
print("To:")
print("\tThe Class Teacher,")
print("\t",standard)
print(" ")
print(" ")
print("Respected",gender)
print(" ")
print("\tSubject:",sub)
print(" ")
print("\tI  am (Your Name), a student of (Class And Section).")
print("\tI want to bring to your kind attention that due to (Mention)")
print("\tyour reason), I will be unable to come to school from (date) to (date).")
print(" ")
print("\t\t\tThanking You")
print(" ")
print("Date:",date)
print("Place:",place)
print("\t\t\t\t\tYours Faithfully")
print("\t\t\t\t\t",name)
