print(" ")
print("\t\t\tLeave Letter")
print(" ")
print("From:")
print("\tM. Yogesh Kumar,")
print(" ")
print("To:")
print("\tThe Class Teacher,")
print(" ")
print(" ")
print("Respected Sir,")
print(" ")
print("\tSubject: Application for Leave")
print(" ")
print("\tI  am (Your Name), a student of (Class And Section).")
print("\tI want to bring to your kind attention that due to (Mention)")
print("\tyour reason), I will be unable to come to school from (date) to (date).")
print(" ")
print("\t\t\tThanking You")
print(" ")
print("Date: 23.03.2023 \t\t\t\t\t\tYours Faithfully,")
print("Place: Madurai\t\t\t\t\t\t\tM. Yogesh Kumar")



